[workspace.package]
version = "0.1.0"
authors = ["BlondeBurrito"]
edition = "2021"
rust-version = "1.70"
readme = "README.md"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/BlondeBurrito/bevy_flowfield_tiles_plugin"
repository = "https://github.com/BlondeBurrito/bevy_flowfield_tiles_plugin"
keywords = ["navigation", "pathfinding", "bevy"]
categories = ["game development", "algorithms"]
exclude = [".github/", "crates/", "assets/"]

[workspace]
members = ["crates/*"]
# Centralised way of managing versions across all crates and packages
[workspace.dependencies]
example_crate = { path = "crates/example_crate" }
bevy = { git = "https://github.com/bevyengine/bevy", rev = "e9312254d8906e9f491c4f3761659df0d179687f", default-features = false, features = [ "ktx2", "zstd" ] }
petgraph = "0.6"

[package]
name = "bevy_flowfield_tiles_plugin"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "An implementation"
readme.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5"

[dependencies]
example_crate = { workspace = true }
bevy = { workspace = true }
petgraph = { workspace = true }

[profile.dev]
opt-level = 1

[profile.flamegraph]
inherits = "release"
debug = true
strip = false

[profile.release]
codegen-units = 1
strip = true # strip symbols to reduce binary size on linux and mac

[[bench]]
name = "fib"
harness = false

[[example]]
name = "hello"
path = "examples/hello.rs"