[workspace.package]
version = "0.1.0"
authors = ["BlondeBurrito"]
edition = "2021"
rust-version = "1.70"
readme = "README.md"
homepage = "https://github.com/BlondeBurrito/repo_template"
repository = "https://github.com/BlondeBurrito/repo_template"
keywords = ["utility"]

[workspace]
members = ["crates/*"]
# Centralised way of managing versions across all crates and packages
[workspace.dependencies]
example_crate = { path = "crates/example_crate" }

[package]
name = "repo_template"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A skeleton repo containing the configuration files for tools which I find useful in Rust development"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.5"

[dependencies]
example_crate = { workspace = true }

[profile.dev]
opt-level = 1

[profile.flamegraph]
inherits = "release"
debug = true
strip = false

[profile.release]
codegen-units = 1
strip = true # strip symbols to reduce binary size on linux and mac

[[bench]]
name = "fib"
harness = false

[[example]]
name = "hello"
path = "examples/hello.rs"