dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "Bresenham",
    "Bresenham's",
    "Eikonal",
    "FBM",
    "PDE",
    "SMAA",
    "Sobel",
    "Subpage",
    "astar",
    "automations",
    "borderless",
    "clippy",
    "clogu",
    "costfield",
    "costfields",
    "despawn",
    "despawned",
    "despawning",
    "dotenvy",
    "earlydawngames",
    "esc",
    "fieldcell",
    "flowfield",
    "flowfields",
    "fullscreening",
    "fxaa",
    "gameplay",
    "greyscale",
    "heightmap",
    "hsv",
    "integrationfield",
    "integrationfields",
    "interactable",
    "intfield",
    "intfields",
    "keybind",
    "keybinds",
    "ktx",
    "lookups",
    "msaa",
    "navmesh",
    "oob",
    "pathable",
    "pathed",
    "pathfinding",
    "pathing",
    "perlin",
    "petgraph",
    "phf",
    "pickable",
    "pollable",
    "programmatically",
    "puml",
    "raws",
    "renet",
    "replayable",
    "replicon",
    "rngs",
    "serde",
    "tform",
    "vsync",
    "wavefronts",
    "wgpu",
    "wip",
    "wireframes",
    "xyz",
]
