dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "FBM",
    "SMAA",
    "Sobel",
    "Subpage",
    "automations",
    "borderless",
    "clippy",
    "despawn",
    "despawned",
    "despawning",
    "dotenvy",
    "earlydawngames",
    "esc",
    "flowfield",
    "fullscreening",
    "fxaa",
    "gameplay",
    "heightmap",
    "hsv",
    "interactable",
    "keybind",
    "keybinds",
    "ktx",
    "lookups",
    "msaa",
    "navmesh",
    "pathfinding",
    "perlin",
    "phf",
    "pickable",
    "programmatically",
    "raws",
    "renet",
    "replayable",
    "replicon",
    "rngs",
    "serde",
    "tform",
    "vsync",
    "wgpu",
    "wip",
    "wireframes",
]
