@startuml int_field_los_prop4

label 1 [
{{
title
IntegrationField LOS Corner
|<#e69138>\n  WB  \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|<#e69138>\n  WB  \n|<#b6d7a8>\n LOS \n|
|<#e69138>\n  WB  \n|<#e69138>\n  WB  \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|<#e69138>\n  WB  \n|<#e69138>\n  WB  \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|<#e69138>\n  WB  \n|<#e69138>\n  WB  \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|<#e69138>\n  WB  \n|<#e69138>\n  WB  \n|\n LOS \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|\n LOS \n|<#ffe599>\n   C   \n|<#000000>\n   X   \n|<#000000>\n   X   \n|<#000000>\n   X   \n|<#ffe599>\n   C   \n|\n LOS \n|\n LOS \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n   0   \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|\n LOS \n|<#b6d7a8>\n LOS \n|
|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|<#b6d7a8>\n LOS \n|
end title
}}

]
@enduml
