@startuml int_field_prop3

title
IntegrationField Propagation 3

|\n   ?   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|\n   ?   \n|
|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|
|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|\n   0   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|
|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|
|\n   ?   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|\n   ?   \n|
end title
@enduml
