@startuml int_field_prop1

title
IntegrationField Propagation 1

|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|
|\n   ?   \n|\n   ?   \n|<#ffe599>\n   1   \n|\n   ?   \n|\n   ?   \n|
|\n   ?   \n|<#ffe599>\n   1   \n|\n   0   \n|<#ffe599>\n   1   \n|\n   ?   \n|
|\n   ?   \n|\n   ?   \n|<#ffe599>\n   1   \n|\n   ?   \n|\n   ?   \n|
|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|\n   ?   \n|
end title
@enduml
