@startuml int_field_prop2

title
IntegrationField Propagation 2

|\n   ?   \n|\n   ?   \n|<#b6d7a8>\n   2   \n|\n   ?   \n|\n   ?   \n|
|\n   ?   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|\n   ?   \n|
|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|\n   0   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|
|\n   ?   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|\n   ?   \n|
|\n   ?   \n|\n   ?   \n|<#b6d7a8>\n   2   \n|\n   ?   \n|\n   ?   \n|
end title
@enduml
