@startuml int_field_prop_impassable

title
IntegrationField Propagation
Impassable
|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|
|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|
|\n   0   \n|<#ffe599>\n   1   \n|<#000000>\n   X   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|
|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#000000>\n   X   \n|<#000000>\n   X   \n|<#e06666>\n   7   \n|
|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#000000>\n   X   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|
end title
@enduml
