@startuml int_field_prop_big_example

title
IntegrationFields Big Example
Goal at 0, Sector (0, 2); Actor at A, Sector (2, 0)

|<#570000>\n  17   \n|<#4a2907>\n  16   \n|<#660000>\n  15   \n|<#b46d23>\n  14   \n|<#274e13>\n  13   \n|<#073763>\n  12   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|
|<#4a2907>\n  16   \n|<#660000>\n  15   \n|<#b46d23>\n  14   \n|<#274e13>\n  13   \n|<#073763>\n  12   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|
|<#660000>\n  15   \n|<#b46d23>\n  14   \n|<#274e13>\n  13   \n|<#073763>\n  12   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|
|<#b46d23>\n  14   \n|<#274e13>\n  13   \n|<#073763>\n  12   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#946cba>\n   P   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|\n   A   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|
|<#274e13>\n  13   \n|<#073763>\n  12   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#946cba>\n   P   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|
|<#073763>\n  12   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|
|<#000000>\n   x   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|
|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|
|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#ffe599>\n   1   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|
|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#ffe599>\n   1   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|
|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#073763>\n  12   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#946cba>\n   P   \n|<#7f6000>\n  10   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#946cba>\n   P   \n|<#a64d79>\n  11   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#e69138>\n   5   \n|<#946cba>\n   P   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#946cba>\n   P   \n|<#a64d79>\n  11   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|
|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#a64d79>\n  11   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#000000>\n   x   \n|
|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#000000>\n   x   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#7f6000>\n  10   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|
|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#000000>\n   x   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#990000>\n   9   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|
|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#946cba>\n   P   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#000000>\n   x   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#cc0000>\n   8   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|
|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#e06666>\n   7   \n|<#bf9000>\n   6   \n|<#946cba>\n   P   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|
|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#bf9000>\n   6   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|
|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#e69138>\n   5   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#000000>\n   x   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|
|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#d5a6bd>\n   4   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|
|<#ffe599>\n   1   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#000000>\n   x   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#a2c4c9>\n   3   \n|<#b6d7a8>\n   2   \n|<#ffe599>\n   1   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|
|<#bf9000>\n   6   \n|<#946cba>\n   P   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#274e13>\n  13   \n|<#946cba>\n   P   \n|<#660000>\n  15   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#946cba>\n   P   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#946cba>\n   P   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#946cba>\n   P   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|13|
|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#000000>\n   x   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|<#b46d23>\n  14   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#073763>\n  12   \n|
|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#000000>\n   x   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|
|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#946cba>\n   P   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|
|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|
|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#946cba>\n   P   \n|<#946cba>\n   P   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|
|\n   0   |<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|
|<#ffe599>\n   1   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#000000>\n   x   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|
|<#b6d7a8>\n   2   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|<#b46d23>\n  14   \n|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|
|<#a2c4c9>\n   3   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#000000>\n   x   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|<#b46d23>\n  14   \n|<#660000>\n  15   \n|<#d5a6bd>\n   4   \n|<#e69138>\n   5   \n|<#bf9000>\n   6   \n|<#e06666>\n   7   \n|<#cc0000>\n   8   \n|<#990000>\n   9   \n|<#7f6000>\n  10   \n|<#a64d79>\n  11   \n|<#073763>\n  12   \n|<#274e13>\n  13   \n|

end title
@enduml
