@startuml sectors_portals

title
Sectors with Portals
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#946cba>\n   1   \n|<#946cba>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#946cba>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#f4cccc>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#946cba>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|<#b6d7a8>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#946cba>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#946cba>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#946cba>\n   1   \n|<#946cba>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#9fc5e8>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|<#f6b26b>\n   1   \n|
end title
@enduml
