name: MacOS

on:
  push:
    branches: [ none ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always
    
jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: deps
        run: brew install michaeleisel/zld/zld
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --workspace
  build:
    name: build
    runs-on: macos-latest
    steps:
      - name: deps
        run: brew install michaeleisel/zld/zld
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --workspace
