name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always
    
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Nix dependencies
        run: sudo apt-get update; sudo apt-get -y install libasound2-dev libudev-dev lld
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --release --workspace
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Nix dependencies
        run: sudo apt-get update; sudo apt-get -y install libasound2-dev libudev-dev lld
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --workspace
