name: Code-cov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  code_cov:
    name: code_cov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Nix dependencies
        uses: ./.github/actions/install_linux_deps
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo install cargo-llvm-cov
          cargo llvm-cov --profile codecov --workspace --all-features --fail-under-lines 85
