name: Doc-cov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always
    
jobs:
  doc_cov:
    name: doc_cov
    runs-on: ubuntu-latest
    steps:
      - name: Nix dependencies
        run: sudo apt-get update; sudo apt-get -y install libasound2-dev libudev-dev lld
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: |
          export RUSTDOCFLAGS="-Z unstable-options --show-coverage"
          cargo +nightly doc --workspace --all-features --no-deps --release
